# Generated by Django 2.2.7 on 2019-12-30 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vechiles', '0002_auto_20191230_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vechiles.Location'),
        ),
    ]
