# Generated by Django 2.2.7 on 2019-12-30 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vechiles', '0003_location_parent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
